services:
    gomobile.sdk.api:
        class: Gomobile\GomobileBundle\src\Gomobile
        public: true
        arguments:
            - "%gomobile.login%"
            - "%gomobile.password%"
            - true